version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: rws_postgres
    environment:
      POSTGRES_DB: rws_blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/migrations:/docker-entrypoint-initdb.d
    networks:
      - rws_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: rws_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rws_network

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rws_backend
    environment:
      APP_ENV: local
      APP_KEY: base64:YOUR_APP_KEY_HERE
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: rws_blog
      DB_USERNAME: postgres
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - postgres
      - redis
    networks:
      - rws_network
    command: >
      sh -c "composer install &&
             php artisan key:generate &&
             php artisan migrate --force &&
             php artisan db:seed --force &&
             php artisan serve --host=0.0.0.0 --port=8000"

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rws_frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000/api
      NEXT_PUBLIC_FRONTEND_URL: http://localhost:3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - rws_network
    command: >
      sh -c "npm install &&
             npm run dev"

  # Mail testing (optional)
  mailpit:
    image: axllent/mailpit
    container_name: rws_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    volumes:
      - mailpit_data:/data
    networks:
      - rws_network

volumes:
  postgres_data:
  redis_data:
  mailpit_data:

networks:
  rws_network:
    driver: bridge